import os
import shutil
from datetime import datetime
from pathlib import Path

import h5py
import pandas as pd


def dataframe_to_picasso(dataframe, filename, extension=None, yaml_dump=None):
    """
    Save a DataFrame in Picasso format (.hdf5 + copied .yaml sidecar).

    Writes the DataFrame to an .hdf5 file under the 'locs' key, and copies the
    matching .yaml sidecar (which must sit next to `filename`), optionally
    appending extra lines to it.

    Parameters
    ----------
    dataframe : pd.DataFrame
        Data in Picasso format (with all required columns).
    filename : str
        Base filename used to build the output paths.
    extension : str
        Suffix appended to the output .hdf5 and .yaml names (must be
        non-empty, e.g. '_event').
    yaml_dump : str, optional
        Extra text appended (line by line) to the copied .yaml. Default None.

    Returns
    -------
    None
    """
    if not extension:
        # An empty extension would overwrite the input file (and None would
        # produce a literal '...None.hdf5'), so require a real suffix.
        raise ValueError("extension must be a non-empty suffix, e.g. '_event'.")
    path = Path.cwd()
    labels = list(dataframe.keys())
    df_picasso = dataframe.reindex(columns=labels, fill_value=1)
    locs = df_picasso.to_records(index=False)
    # Get the full path of the original YAML file
    yaml_old = Path(filename).with_suffix(".yaml")  # Ensures correct extension handling
    # Construct new YAML filename
    if extension:
        yaml_new = yaml_old.with_name(f"{yaml_old.stem}{extension}.yaml")
    else:
        yaml_new = yaml_old
    try:
        # Ensure the original YAML file exists
        if not yaml_old.exists():
            print(f"Error: The file '{yaml_old}' was not found.")
            return
        # Copy and optionally modify the YAML file
        shutil.copyfile(yaml_old, yaml_new)
        if yaml_dump:
            with open(yaml_new, "a") as file:
                file.writelines([f"{line.strip()}\n" for line in yaml_dump.split("\n")])
    except Exception as e:
        print(f"An unexpected error occurred: {e}")
    # filename[:-5] strips the 5-char '.hdf5'/'.yaml' extension; assumes that exact length
    hf = h5py.File(path / f"{filename[:-5]}{extension}.hdf5", "w")
    hf.create_dataset("locs", data=locs)
    hf.close()
    print("\ndataframe successfully saved in picasso format.")


def process_input(input_data, dataset):
    """
    Return a DataFrame from either a file path or an existing DataFrame.

    Parameters
    ----------
    input_data : str or pd.DataFrame
        A path to a '.hdf5' / '.txt' file, or an already-loaded DataFrame.
    dataset : str
        Which dataset to read from a file: 'locs', 'photons', or 'drift'.
        ('drift' is read as a space-delimited table with columns 'x', 'y'.)

    Returns
    -------
    pd.DataFrame
        The resulting DataFrame.

    Raises
    ------
    ValueError
        If `dataset` is not one of 'locs', 'photons', 'drift', or if the file
        cannot be read.
    TypeError
        If `input_data` is neither a supported path nor a DataFrame.
    """
    if isinstance(input_data, str) and input_data.endswith((".hdf5", ".txt")):
        if dataset not in ("locs", "photons", "drift"):
            raise ValueError(
                f"Unknown dataset '{dataset}'; expected 'locs', 'photons', or 'drift'."
            )
        # Attempt to read the file
        try:
            if dataset in ("locs", "photons"):
                data = pd.read_hdf(input_data, key=dataset)
            elif dataset == "drift":
                data = pd.read_csv(input_data, delimiter=" ", names=["x", "y"])
            return data
        except Exception as e:
            raise ValueError(f"Failed to read the input file: {e}")
    elif isinstance(input_data, pd.DataFrame):
        return input_data
    else:
        raise TypeError(
            "Input must be a string ending with '.txt', '.hdf5' or a pandas DataFrame."
        )


def create_append_message(function, **info):
    """
    Build a provenance message string from keyword metadata.

    Each item in `info` becomes a line; keys containing 'file' are expanded to
    absolute paths. A timestamp is appended at the end.

    Parameters
    ----------
    function : str
        Name of the generating function (recorded in the message).
    **info
        Arbitrary key-value metadata to record.

    Returns
    -------
    str
        The formatted, multi-line provenance message.
    """
    message = f"\n---\nGenerated by: {function}"
    for key, value in info.items():
        if "file" in key.lower():
            try:
                full_path = os.path.abspath(value)
                message += f"\n{key} (full path): {full_path}"
            except Exception as e:
                message += f"\n{key}: {value} (could not retrieve full path: {e})"
        else:
            message += f"\n{key}: {value}"
    # Append the current date and time
    current_time = datetime.now().strftime("%Y-%m-%d %H:%M:%S")
    message += f"\nTimestamp: {current_time}"
    return message
